services:
  web:
    image: ${DOCKER_REGISTRY-}web
    restart: unless-stopped
    build:
      context: ./fe
      dockerfile: Dockerfile

  host:
    image: ${DOCKER_REGISTRY-}host
    restart: unless-stopped
    deploy:
      replicas: 2
    build:
      context: .
      dockerfile: src/Host/Dockerfile

  seq:
    image: datalust/seq:latest
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      ACCEPT_EULA: Y
      SEQ_BASE_URI: http://seq:5341

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "--raw", "incr", "ping"]

  selenium-hub:
    image: selenium/hub:latest
    restart: unless-stopped
    ports:
      - 4444:4444
    environment:
      - GRID_MAX_SESSION=10  # Max parallel sessions
      - GRID_BROWSER_TIMEOUT=120
      - GRID_TIMEOUT=300

  selenium-node-chrome:
    image: selenium/node-chrome:latest
    restart: unless-stopped
    depends_on:
      - selenium-hub
    deploy:
      replicas: 2
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=5              # Each node handles 5 sessions
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true  # Override default limit

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - 8888:8888
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - host